#! /bin/sh

# Keybinds
sxhkd &

# BSPC Config
# @TODO need to configure this here and in polybar
bspc monitor eDP1  -d 1 2 3 4 
bspc monitor DP1  -d 5 6 7 8

bspc config border_width         4
bspc config window_gap          12

bspc config normal_border_color "#888888"
bspc config focused_border_color "#FFFFFF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Applications
#bspc rule -a Chromium desktop='^2'
# Not sure why we need to quote this
#bspc rule -a "discord" desktop='^6' follow=on 
#bspc rule -a Slack desktop='^7'
